/**
 * NOTE: This class is auto generated by the panchtantra code generator program (2.4.15).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.adobe.panchtantra.api;

import com.adobe.panchtantra.model.*;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.panchtantra.codegen.languages.SpringCodegen", date = "2020-09-24T08:39:55.612Z")

@Api(value = "inventory", description = "the inventory API")
public interface InventoryApi {

    @ApiOperation(value = "Save BookingModel.", nickname = "saveBookingsByInventoryId", notes = "Save BookingModel.", tags={ "BookingModel", })
    @ApiResponses(value = { 
        @ApiResponse(code = 204, message = "BookingModel saved successfully.") })
    @RequestMapping(value = "/inventory/{inventoryId}/booking",
        method = RequestMethod.POST)
    ResponseEntity<Void> saveBookingsByInventoryId(@ApiParam(value = "inventoryId",required=true) @PathVariable("inventoryId") Long inventoryId,@ApiParam(value = "BookingModel Object."  )  @Valid @RequestBody BookingModel booking);


    @ApiOperation(value = "Save InventoryEntity.", nickname = "saveInventory", notes = "Save InventoryEntity.", tags={ "InventoryEntity", })
    @ApiResponses(value = { 
        @ApiResponse(code = 204, message = "InventoryEntity saved successfully.") })
    @RequestMapping(value = "/inventory",
        method = RequestMethod.POST)
    ResponseEntity<Void> saveInventory(@ApiParam(value = "InventoryEntity Object."  )  @Valid @RequestBody InventoryModel inventory);
    
    @ApiOperation(value = "Get Inventories.", nickname = "getInventories", notes = "Get InventoryEntity.", tags={ "InventoryEntity", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "successful operation", response = Inventories.class) })
    @RequestMapping(value = "/inventory",
            produces = { "application/json" },
            method = RequestMethod.GET)
    ResponseEntity<Inventories> getInventories(@RequestParam("packageId") String packageId, @RequestParam("startDate") String startDate, @RequestParam("endDate") String endDate);
    

}
