/**
 * NOTE: This class is auto generated by the panchtantra code generator program (2.4.15).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.adobe.panchtantra.api;

import com.adobe.panchtantra.model.Otts;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@javax.annotation.Generated(value = "io.panchtantra.codegen.languages.SpringCodegen", date = "2020-09-24T08:39:55.612Z")

@Api(value = "otts", description = "the otts API")
@RequestMapping(value = "/Panchtantra/Parasites/1.0.0")
public interface OttsApi {

    @ApiOperation(value = "Find OTTs", nickname = "getAllOtts", notes = "Find OTT", response = Otts.class, tags={ "OTT", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Otts.class),
        @ApiResponse(code = 400, message = "Bad Request"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/otts",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Otts> getAllOtts();

}
