/**
 * NOTE: This class is auto generated by the panchtantra code generator program (2.4.15).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.adobe.panchtantra.api;

import com.adobe.panchtantra.model.Bookings;
import com.adobe.panchtantra.model.Inventories;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@javax.annotation.Generated(value = "io.panchtantra.codegen.languages.SpringCodegen", date = "2020-09-24T08:39:55.612Z")

@Api(value = "user", description = "the user API")
@RequestMapping(value = "/Panchtantra/Parasites/1.0.0")
public interface UserApi {

    @ApiOperation(value = "Retrieve bookings for user", nickname = "getBookingsByUserId", notes = "Retrieve bookings for user", response = Bookings.class, tags={ "BookingModel", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Bookings.class),
        @ApiResponse(code = 400, message = "Invalid ID"),
        @ApiResponse(code = 404, message = "Bookings not found") })
    @RequestMapping(value = "/user/{userId}/bookings",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Bookings> getBookingsByUserId(@ApiParam(value = "userId",required=true) @PathVariable("userId") Long userId);


    @ApiOperation(value = "Retrieve inventories for user", nickname = "getInventoriesByUserId", notes = "Retrieve inventories for user", response = Inventories.class, tags={ "InventoryEntity", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Inventories.class),
        @ApiResponse(code = 400, message = "Invalid ID"),
        @ApiResponse(code = 404, message = "Inventories not found") })
    @RequestMapping(value = "/user/{userId}/inventories",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Inventories> getInventoriesByUserId(@ApiParam(value = "userId",required=true) @PathVariable("userId") Long userId);

}
